export const projects=[
  //{id:0,image:'/images/generateur.jpg',title: 'Générateur de cv', description: 'Générateur de cv est un site internet pour permettre de créer son cv en ligne',tech:['Html','Css','Bootstrap','Php','Mysql'],demo:'http://generateurcv.ndongodahs.fr/',code:'https://github.com/ndongo78/generateurcv',status:'Terminé'},
  {id:1,image:'/images/adil.png',title:'Adil Shopping',description:'Adil Shopping est un site ecommerce qui vend des produits vétements , chaussures , accessoires. Laravel comme api', tech:['React' , 'Laravel' , 'ReactBootstrap' , 'Mysql'] , demo:'https://ndongoshop.netlify.app',code:'https://github.com/ndongo78/front_end',status:'En maintenance'},
  //{id:2,image:'/images/blog.png',title:'JePartage',description:'JePartage est un réseau social permettant aux utilisateur de partager tous les événements  de leur vie ' ,tech:['Vue' , 'Vuex' , 'Tailwindcss' ,'Node','Sequelize','Mysql'],demo:'http://',code:'http://',status:'En cours'},
  {id:3,image:'/images/kadim.png',title:'Khadim Boutique',description:'Khadim Boutique est un site ecommerce qui vend des produits multimédia (Smartphones,Ordinateurs et accéssoires multimédia)',tech:['React','MaterialUi','Redux','Node','Sequelize','Mysql'],demo:'https://khadimshop.vercel.app/',code:'https://github.com/ndongo78/khadimshop',status:'Terminé'},
  {id:5,image:'/images/letchat.png',title:'letchat',description:'letchat une site web qui permet de chat avec ses amis et proches.On peut envoyer des images,emojis ...',tech:['React','Firebase','chatEngine',"MaterialUi"],demo:'https://letchat.ndongodahs.fr/',code:'https://github.com/ndongo78/portfolio',status:'Terminé'},
  {id:6,image:'/images/chatVideo.png',title:'VideoCall',description:"VideoCall une site web qui permet d'appeler en video ses amis et proches",tech:['React','Nodejs','Socket.io',"MaterialUi"],demo:'https://my-video-chat.vercel.app/',code:'https://github.com/ndongo78/myVideoChat',status:'Terminé'},
  {id:4,image:'/images/lami.jpg',title:'Lami app',description:"LAMI est une application de réseau sociale permettant aux utilisateur de se connecter entre eux mais aussi de récompensé , de payer ou de vendre des services",tech:['React native','Redux','Node','Express','Mysql'],demo:'https://expo.dev/@ndongodahr/lamiapp',code:'http://',status:'Terminé'},
  {id:7,image:'/images/music.jpg',title:'My player',description:"My player est une application de music player.Elle permet de lire les audios disponible localement depuis le stockage du mobile",tech:['React native',"TypeScript"],demo:'https://',code:'https://github.com/ndongo78/RNPlayer',status:'Terminé'},
  {id:8,image:'/images/currency_converter.png',title:'Currency converter',description:"Currency converter est une application de convertisseuse devise.Plusieurs devises sont disponibles",tech:['React native'],demo:'https://',code:'https://github.com/ndongo78/convertisseur_devises.git',status:'Terminé'},
  {id:9,image:'/images/chatndongo.jpg',title:'chatndongo',description:"Chatndongo est une application de chat via message , appel video et appel audio.Elle permet aux utilisateurs de s'échanger depuis leur mobile",tech:['React native',"TypeScript","Node","socket.io","Mysql"],demo:'https://',code:'https://github.com/ndongo78/chat_front',status:'En cours'},
  {id:10,image:'/images/shoper.png',title:'Shop it',description:"Shop it est une application d'ecommerce.Elle permet à ses clients d'acheter des produits en ligne ",tech:['React native',"TypeScript","Node","PostgreSQL"],demo:'https://',code:'https://github.com/ndongo78/shop_mobile.git',status:'En cours'},
]
